# load_module modules/ngx_http_js_module.so;

# Пробрасываем переменные окружения в Nginx
env WEBDIS_HOST;
env WEBDIS_PORT;

events {}

http {
    charset utf-8;

    resolver 127.0.0.11 ipv6=off;

    js_import main from /etc/nginx/js/main.js;
    js_import api from /etc/nginx/js/api.js;
    js_import app from /etc/nginx/js/app.js;
    js_import app2 from /etc/nginx/js/app2.js;
    js_import app3 from /etc/nginx/js/app3.js;
    js_import app4 from /etc/nginx/js/app4.js;
    js_import signer from /etc/nginx/js/signer.js;
    js_import check_sign from /etc/nginx/js/check_sign.js;


    error_log /var/log/nginx/error.log debug;
    
    upstream redis_http {
        server webdis:7379;
    }

    proxy_cache_path /var/cache/nginx keys_zone=backend_cache:100m max_size=10g inactive=1h use_temp_path=off;


    # Переменная для прокси
    map "" $new_signed_url { default ""; }

    server {
        listen 80;

        location /hello {
            js_content main.hello;
        }

        location /echo {
            js_content api.echo;
        }

        location /app {
            js_content app.router;
        }

        location /app2 {
            js_content app2.router;
        }

        location /app3 {
            js_content app3.router;
        }

        location /app4 {
            js_content app4.router;
        }

        location /redis/ {
            proxy_pass http://redis_http/;
            proxy_buffering on;
            proxy_buffers 4 16k;
            proxy_busy_buffers_size 16k;
        }


        location /favicon.ico {
            access_log off;
            return 200;
        }

        # Клиент обращается сюда
        location /v1/ {
            js_content signer.rewrite_and_proxy;
        }

        # Прокси на origin
        location @backend {
            proxy_pass $new_signed_url;
        }

        location ~ ^/v2/(?<filepath>[a-z]+\/[a-f0-9]+)/(?<sign>[a-f0-9]+):(?<time>\d+)/(?<filename>.+)$ {
       
            js_set $is_valid check_sign;

            if ($is_valid = "0") {
                return 403;
            }

            proxy_cache backend_cache;
            proxy_cache_valid 200 1h;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            proxy_cache_lock on;

            proxy_pass http://backend/$filepath/$sign:$time/$filename;
        }

    }
}